/**
 * Assembles the AppSail deploy bundle from a Next standalone build.
 *
 * WHY THIS EXISTS
 *
 * The Catalyst CLI packs and uploads whatever sits in the build path. It does
 * NOT install dependencies, so the upload has to be self-contained — and
 * uploading the whole of `node_modules` is not viable, because the packer
 * opens a read stream for every file at once and Windows answers EMFILE.
 *
 * `output: "standalone"` solves that (about 2,700 files instead of 59,500),
 * but Next leaves three gaps that have to be filled by hand every time:
 *
 *   1. `.next/static` is not copied into the bundle — without it every script
 *      and stylesheet 404s and the app renders unstyled and dead.
 *   2. `public/` is not copied either.
 *   3. `next build` DELETES `.next/standalone`, so anything added there by
 *      hand disappears on the next build. That is exactly what happened: the
 *      start shim vanished and the bundle would not boot.
 *
 * Run this after `next build`, then deploy. Never hand-edit the bundle.
 *
 *   npm run pack:appsail
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const STANDALONE = path.join(ROOT, ".next", "standalone");

function die(message) {
  console.error("[pack] " + message);
  process.exit(1);
}

if (!fs.existsSync(STANDALONE)) {
  die("no .next/standalone — run `npm run build` first (needs output: 'standalone').");
}

const copyDir = (from, to, label) => {
  if (!fs.existsSync(from)) return console.log(`[pack] ${label}: nothing at ${from}, skipped`);
  fs.cpSync(from, to, { recursive: true });
  const count = fs.readdirSync(to, { recursive: true }).length;
  console.log(`[pack] ${label}: ${count} entries -> ${path.relative(ROOT, to)}`);
};

// 1. Client assets. Without these the pages load but nothing works.
copyDir(path.join(ROOT, ".next", "static"), path.join(STANDALONE, ".next", "static"), "static");
copyDir(path.join(ROOT, "public"), path.join(STANDALONE, "public"), "public");

// 2. The port shim. Next's server.js reads PORT; Catalyst announces the port
//    as X_ZOHO_CATALYST_LISTEN_PORT, so nothing listens where the platform is
//    routing and the instance is killed as unhealthy.
const startJs = `/**
 * AppSail entry point — generated by scripts/pack-appsail.js. Do not edit here;
 * it is overwritten on every pack.
 *
 * Next's server.js binds process.env.PORT || 3000. Catalyst routes to the port
 * in App Execution Settings and announces it as X_ZOHO_CATALYST_LISTEN_PORT,
 * which Next knows nothing about — so the server listened on 3000, nothing
 * answered on 9000, and the platform reported "Execution failed. Please check
 * the startup command or port" with zero live instances.
 *
 * The translation must happen BEFORE server.js is required: Next reads the
 * port at module load.
 */
const port =
  process.env.X_ZOHO_CATALYST_LISTEN_PORT ||
  process.env.X_ZOHO_CATALYST_SERVER_LISTEN_PORT ||
  process.env.PORT ||
  "3000";

process.env.PORT = String(port);

// Bind every interface: the platform's health check does not come from
// localhost, so a server on 127.0.0.1 is invisible to it.
process.env.HOSTNAME = process.env.HOSTNAME || "0.0.0.0";

console.log("[orca] standalone server starting on " + process.env.HOSTNAME + ":" + process.env.PORT);

require("./server.js");
`;
fs.writeFileSync(path.join(STANDALONE, "start.js"), startJs, "utf8");
console.log("[pack] start.js written");

/*
 * 3. The bundle carries its OWN app-config.json so the test service never
 *    borrows the root one. That keeps orca-dashboard's configuration entirely
 *    separate from anything done here.
 */
const appConfig = {
  name: "orca-dashboard-test",
  stack: "node24",
  command: "node start.js",
  build_path: ".",
  memory: 1024,
};
fs.writeFileSync(
  path.join(STANDALONE, "app-config.json"),
  JSON.stringify(appConfig, null, 2) + "\n",
  "utf8"
);
console.log("[pack] app-config.json written");

// 4. Refuse to hand over a bundle that cannot boot.
const required = ["server.js", "start.js", "app-config.json", "node_modules", ".next/static"];
const missing = required.filter((r) => !fs.existsSync(path.join(STANDALONE, r)));
if (missing.length) die("bundle is incomplete, missing: " + missing.join(", "));

const files = fs.readdirSync(STANDALONE, { recursive: true }).length;
console.log(`[pack] bundle ready: ${files} entries in .next/standalone`);
if (files > 20000) {
  console.warn("[pack] WARNING: that is a lot of files — the packer may hit EMFILE again.");
}
